site_name: Develop Cloud Connected Mobile Apps with Xamarin and Microsoft Azure
site_url: https://adrianhall.github.io/develop-mobile-apps-with-csharp-and-azure/
repo_url: https://github.com/adrianhall/develop-mobile-apps-with-csharp-and-azure
repo_name: GitHub
site_author: Adrian Hall
copyright: 'Copyright &copy; 2017-2019 Adrian Hall'
nav:
    - Getting Started: index.md
theme: material
extra:
    palette:
      primary: 'red'
      accent: 'deep purple'
    social:
    - type: 'github'
      link: 'https://github.com/adrianhall'
    - type: 'twitter'
      link: 'https://twitter.com/FizzyInTheHall'
markdown_extensions:
    - toc:
        permalink: true
    - fenced_code
    - admonition
extra_css:
  - css/extra.css
  - css/vs.css
extra_javascript:
  - js/highlight.pack.js
google_analytics:
  - 'UA-93366112-1'
  - 'auto'
